/**
 * A GraphQL Code Generator plugin that types your `.gql` imports.
 *
 * `@graphql-codegen/typescript-operations` writes `NotesQuery` and
 * `NotesQueryVariables` from your schema. This writes the line that connects
 * them to the file:
 *
 * ```ts
 * declare module '*\/notes.gql' {
 *   const document: GraphQLDocument<NotesQuery, NotesQueryVariables>;
 *   export default document;
 * }
 * ```
 *
 * With that, nothing at a call site carries a type argument, and nothing can
 * drift: the variables are checked against the operation, and the result is
 * the shape the server actually returns.
 *
 * ```ts
 * // codegen.ts
 * import type { CodegenConfig } from '@graphql-codegen/cli';
 *
 * const config: CodegenConfig = {
 *   schema: 'schema.graphql',
 *   documents: 'src/**\/*.gql',
 *   generates: {
 *     'src/graphql-types.ts': { plugins: ['typescript', 'typescript-operations'] },
 *     'src/graphql-modules.d.ts': {
 *       plugins: ['@firsthandjs/data/codegen'],
 *       config: { typesPath: './graphql-types' },
 *     },
 *   },
 * };
 * export default config;
 * ```
 *
 * The declarations use wildcard module names (`*\/notes.gql`), which is how
 * every codegen plugin of this kind works: TypeScript picks the most specific
 * pattern, and the file stays a script rather than a module so the wildcards
 * are legal.
 */

/** The bits of codegen's document shape this needs. Typed here to avoid a dependency. */
export interface CodegenDocument {
  readonly location?: string | undefined;
  readonly document?:
    | {
        readonly definitions: readonly {
          readonly kind: string;
          readonly operation?: string;
          readonly name?: { readonly value: string } | undefined;
        }[];
      }
    | undefined;
}

export interface CodegenConfig {
  /**
   * Where `typescript-operations` wrote its types, relative to this file.
   *
   * Defaults to `./graphql-types`, which is what the example above generates.
   */
  readonly typesPath?: string;
  /** Import path for the document type. Only useful when testing this plugin. */
  readonly documentTypePath?: string;
}

const SUFFIX: Record<string, string> = {
  query: 'Query',
  mutation: 'Mutation',
  subscription: 'Subscription',
};

/** `notes` from `/src/notes.gql`, for the wildcard pattern. */
function moduleName(location: string): string {
  const normalized = location.split('\\').join('/');
  const file = normalized.slice(normalized.lastIndexOf('/') + 1);
  return `*/${file}`;
}

/**
 * The operation a document file declares.
 *
 * A file holding only fragments has none, and gets no declaration — importing
 * it as a document would be a mistake, and leaving it untyped says so.
 */
function operationOf(document: CodegenDocument['document']): { name: string; kind: string } | null {
  for (const definition of document?.definitions ?? []) {
    if (definition.kind === 'OperationDefinition' && definition.name !== undefined) {
      return { name: definition.name.value, kind: definition.operation ?? 'query' };
    }
  }
  return null;
}

/**
 * Generates the module declarations.
 *
 * The signature is GraphQL Code Generator's: `(schema, documents, config)`.
 * The schema is unused — the operation types come from the plugins that ran
 * before this one.
 */
export function plugin(
  _schema: unknown,
  documents: readonly CodegenDocument[],
  config: CodegenConfig = {},
): string {
  const typesPath = config.typesPath ?? './graphql-types';
  const documentType = config.documentTypePath ?? '@firsthandjs/data';
  const blocks: string[] = [];
  const declared = new Set<string>();

  for (const entry of documents) {
    const location = entry.location;
    if (location === undefined || location === '') {
      continue;
    }
    const operation = operationOf(entry.document);
    if (operation === null) {
      continue;
    }
    const name = moduleName(location);
    if (declared.has(name)) {
      continue;
    }
    declared.add(name);

    // `typescript-operations` names types `<Operation><Kind>` and
    // `<Operation><Kind>Variables`; this is the same convention, read from the
    // same document.
    const base = `${operation.name}${SUFFIX[operation.kind] ?? 'Query'}`;
    blocks.push(
      [
        `declare module '${name}' {`,
        `  const document: import('${documentType}').GraphQLDocument<`,
        `    import('${typesPath}').${base},`,
        `    import('${typesPath}').${base}Variables`,
        `  >;`,
        `  export default document;`,
        `}`,
      ].join('\n'),
    );
  }

  return [
    '// Generated by @firsthandjs/data/codegen. Do not edit.',
    '//',
    '// Wildcard module declarations, so that importing a .gql file gives a',
    '// document that knows its own result and variable types. Nothing here is',
    '// a module: wildcards are only legal in a script.',
    '',
    ...blocks,
    '',
  ].join('\n');
}

export default { plugin };
